defmodule Tauros.Accounts.Agent do
  @moduledoc """
  An AI or service principal that acts on behalf of the human who registered it.

  Agents authenticate with an API key (AshAuthentication `api_key` strategy).
  The key is generated by Tauros, returned once, and stored only as a hash.
  An agent is a capability holder, never an authority: only its owning human
  may manage it.
  """
  use Ash.Resource,
    otp_app: :tauros,
    domain: Tauros.Accounts,
    extensions: [AshJsonApi.Resource, AshAuthentication],
    authorizers: [Ash.Policy.Authorizer],
    data_layer: AshPostgres.DataLayer

  alias Tauros.Accounts.Checks.HumanActor

  authentication do
    # Agents never receive tokens (they authenticate per request with an API key),
    # but AshAuthentication's sign-out helpers look up a token resource for every
    # authenticated resource.
    tokens do
      enabled? false
      token_resource Tauros.Accounts.Token
    end

    strategies do
      api_key :api_key do
        api_key_relationship :valid_api_keys
        api_key_hash_attribute :api_key_hash
      end
    end
  end

  json_api do
    type "agent"
  end

  postgres do
    table "agents"
    repo Tauros.Repo

    references do
      reference :user, on_delete: :delete, index?: true
    end
  end

  actions do
    defaults [:read, :destroy]

    create :create do
      primary? true
      accept [:name]
      change relate_actor(:user)
      change Tauros.Accounts.Agent.Changes.IssueApiKey

      metadata :plaintext_api_key, :string do
        description "The issued API key. Returned only by this action; Tauros stores its hash."
        allow_nil? false
      end
    end

    update :update do
      primary? true
      accept [:name]
    end

    update :rotate_api_key do
      description "Revoke the agent's current API key and issue a new one."
      accept []
      require_atomic? false
      # Serialize concurrent rotations so exactly one key survives.
      change get_and_lock_for_update()
      change Tauros.Accounts.Agent.Changes.IssueApiKey

      metadata :plaintext_api_key, :string do
        description "The new API key. Returned only by this action; Tauros stores its hash."
        allow_nil? false
      end
    end

    read :sign_in_with_api_key do
      argument :api_key, :string, allow_nil?: false
      prepare AshAuthentication.Strategy.ApiKey.SignInPreparation
    end
  end

  policies do
    bypass AshAuthentication.Checks.AshAuthenticationInteraction do
      authorize_if always()
    end

    policy always() do
      description "Agents are managed only by the human who owns them"
      forbid_unless HumanActor
      authorize_if action_type(:create)
      authorize_if relates_to_actor_via(:user)
    end
  end

  attributes do
    uuid_primary_key :id

    attribute :name, :string do
      allow_nil? false
      public? true
      constraints trim?: true, min_length: 1, max_length: 160
    end

    timestamps public?: true
  end

  relationships do
    belongs_to :user, Tauros.Accounts.User do
      allow_nil? false
      public? true
    end

    has_many :valid_api_keys, Tauros.Accounts.ApiKey do
      filter expr(valid)
    end

    has_many :customers, Tauros.Revenue.Customer
    has_many :payment_destinations, Tauros.Revenue.PaymentDestination
  end
end
