defmodule Tauros.Repo.Migrations.RenameWalletAccountsToPaymentDestinations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:wallet_accounts), to: table(:payment_destinations)

    alter table(:payment_destinations) do
      add :network, :text
    end

    drop constraint(:payment_destinations, "wallet_accounts_agent_id_fkey")

    alter table(:payment_destinations) do
      modify :agent_id,
             references(:agents,
               column: :id,
               name: "payment_destinations_agent_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    # Edited: ash_postgres generated these renames inside the `alter` block
    # above, which Ecto rejects ("cannot execute nested commands").
    rename table(:payment_destinations), :public_address, to: :address
    rename table(:payment_destinations), :wallet_name, to: :label
  end

  def down do
    drop constraint(:payment_destinations, "payment_destinations_agent_id_fkey")

    rename table(:payment_destinations), :label, to: :wallet_name
    rename table(:payment_destinations), :address, to: :public_address

    alter table(:payment_destinations) do
      modify :agent_id,
             references(:agents,
               column: :id,
               name: "wallet_accounts_agent_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:payment_destinations) do
      remove :network
    end

    rename table(:payment_destinations), to: table(:wallet_accounts)
  end
end
