defmodule Tauros.Repo.Migrations.AddInvoiceEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:invoice_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action, :text, null: false
      add :from_state, :text
      add :to_state, :text, null: false
      add :actor_id, :uuid, null: false
      add :actor_kind, :text, null: false
      add :interface, :text, null: false
      add :payload_hash, :text
      add :idempotency_key, :text
      add :note, :text

      add :occurred_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :invoice_id,
          references(:invoices,
            column: :id,
            name: "invoice_events_invoice_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :revision_id,
          references(:invoice_revisions,
            column: :id,
            name: "invoice_events_revision_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create index(:invoice_events, [:invoice_id])
  end

  def down do
    drop_if_exists index(:invoice_events, [:invoice_id])

    drop constraint(:invoice_events, "invoice_events_revision_id_fkey")

    drop constraint(:invoice_events, "invoice_events_invoice_id_fkey")

    drop table(:invoice_events)
  end
end
