defmodule Tauros.Repo.Migrations.AddInvoicesAndRevisions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:invoice_revisions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :number, :bigint, null: false
      add :currency, :text, null: false
      add :due_date, :date, null: false
      add :lines, {:array, :map}, null: false
      add :total, :decimal, null: false
      add :reasoning, :text, null: false
      add :canonical_payload, :text, null: false
      add :payload_hash, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :invoice_id, :uuid, null: false
    end

    create unique_index(:invoice_revisions, [:invoice_id, :number],
             name: "invoice_revisions_number_per_invoice_index"
           )

    alter table(:invoice_revisions) do
      add :customer_id,
          references(:customers,
            column: :id,
            name: "invoice_revisions_customer_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :payment_destination_id,
          references(:payment_destinations,
            column: :id,
            name: "invoice_revisions_payment_destination_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create table(:invoices, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:invoice_revisions) do
      modify :invoice_id,
             references(:invoices,
               column: :id,
               name: "invoice_revisions_invoice_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create index(:invoice_revisions, [:customer_id])

    create index(:invoice_revisions, [:payment_destination_id])

    alter table(:invoices) do
      add :idempotency_key, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "draft"

      add :agent_id,
          references(:agents,
            column: :id,
            name: "invoices_agent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:invoices, [:agent_id, :idempotency_key],
             name: "invoices_idempotency_key_per_agent_index"
           )
  end

  def down do
    drop constraint(:invoices, "invoices_agent_id_fkey")

    drop_if_exists unique_index(:invoices, [:agent_id, :idempotency_key],
                     name: "invoices_idempotency_key_per_agent_index"
                   )

    alter table(:invoices) do
      remove :agent_id
      remove :state
      remove :updated_at
      remove :inserted_at
      remove :idempotency_key
    end

    drop_if_exists index(:invoice_revisions, [:payment_destination_id])

    drop_if_exists index(:invoice_revisions, [:customer_id])

    drop constraint(:invoice_revisions, "invoice_revisions_payment_destination_id_fkey")

    drop constraint(:invoice_revisions, "invoice_revisions_customer_id_fkey")

    drop constraint(:invoice_revisions, "invoice_revisions_invoice_id_fkey")

    alter table(:invoice_revisions) do
      modify :invoice_id, :uuid
    end

    drop table(:invoices)

    alter table(:invoice_revisions) do
      remove :payment_destination_id
      remove :customer_id
    end

    drop_if_exists unique_index(:invoice_revisions, [:invoice_id, :number],
                     name: "invoice_revisions_number_per_invoice_index"
                   )

    drop table(:invoice_revisions)
  end
end
