defmodule Tauros.Repo.Migrations.RequirePaymentDestinationNetwork do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:payment_destinations) do
      modify :network, :text, null: false
    end
  end

  def down do
    alter table(:payment_destinations) do
      modify :network, :text, null: true
    end
  end
end
