defmodule Tauros.Repo.Migrations.AddPaymentDestinationLifecycle do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:payment_destinations) do
      add :state, :text, null: false, default: "active"

      add :supersedes_id,
          references(:payment_destinations,
            column: :id,
            name: "payment_destinations_supersedes_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create unique_index(:payment_destinations, [:supersedes_id],
             name: "payment_destinations_one_replacement_each_index"
           )
  end

  def down do
    drop constraint(:payment_destinations, "payment_destinations_supersedes_id_fkey")

    drop_if_exists unique_index(:payment_destinations, [:supersedes_id],
                     name: "payment_destinations_one_replacement_each_index"
                   )

    alter table(:payment_destinations) do
      remove :supersedes_id
      remove :state
    end
  end
end
