defmodule Tauros.Repo.Migrations.AddApprovals do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:approvals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :decision, :text, null: false
      add :payload_hash, :text, null: false
      add :reason, :text

      add :decided_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :invoice_id,
          references(:invoices,
            column: :id,
            name: "approvals_invoice_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :revision_id,
          references(:invoice_revisions,
            column: :id,
            name: "approvals_revision_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:approvals, [:revision_id],
             name: "approvals_one_decision_per_revision_index"
           )

    alter table(:approvals) do
      add :approver_id,
          references(:users,
            column: :id,
            name: "approvals_approver_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create index(:approvals, [:invoice_id])

    create index(:approvals, [:approver_id])
  end

  def down do
    drop_if_exists index(:approvals, [:approver_id])

    drop_if_exists index(:approvals, [:invoice_id])

    drop constraint(:approvals, "approvals_approver_id_fkey")

    drop constraint(:approvals, "approvals_revision_id_fkey")

    drop constraint(:approvals, "approvals_invoice_id_fkey")

    alter table(:approvals) do
      remove :approver_id
    end

    drop_if_exists unique_index(:approvals, [:revision_id],
                     name: "approvals_one_decision_per_revision_index"
                   )

    drop table(:approvals)
  end
end
